---

- name: Get macOS version
  set_fact:
    macos_version: "{{ ansible_distribution_version |
                    regex_search('^([0-9]+\\.[0-9]+)') }}"

- name: Install macOS SDK headers for macOS 10.14 (Mojave)
  become: true
  command: "installer -pkg {{ mojave_sdk_headers }} -target /"
  when: macos_version == "10.14"
  args:
    creates: /usr/include

- name: Install pyenv build requirements with Homebrew
  homebrew:
    name: "{{ pyenv_build_requirements }}"

- name: Install with Homebrew
  include_tasks: install_with_homebrew.yml
  when: pyenv_install_from_package_manager|bool

- name: Install with Git
  include_tasks: install_with_git.yml
  when: not pyenv_install_from_package_manager|bool
