---

- name: Get macOS version
  set_fact:
    macos_version: "{{ ansible_distribution_version | regex_search('^([0-9]+\\.[0-9]+)') }}"

- name: Install macOS SDK headers for macOS 10.14 (Mojave)
  become: yes
  command: "installer -pkg {{ mojave_sdk_headers }} -target /"
  when: macos_version == "10.14"
  args:
    creates: /usr/include

- name: Install pyenv build requirements with Homebrew
  package:
    name: "{{ pyenv_build_requirements }}"

- name: Install pyenv with Homebrew
  package:
    name: pyenv

- name: Install pyenv-virtualenv with Homebrew
  package:
    name: pyenv-virtualenv

- name: Install pyenv-virtualenvwrapper with Homebrew
  package:
    name: pyenv-virtualenvwrapper
  when: pyenv_virtualenvwrapper|bool
