---
# tasks file for ansible-pyenv

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Setup on Linux
  include_tasks: Linux.yml
  when: "ansible_system == 'Linux'"

- name: Setup on macOS
  include_tasks: Darwin.yml
  when: "ansible_os_family == 'Darwin'"

- import_tasks: install.yml

- name: Initialise shell
  include_tasks: shell.yml
  when: pyenv_init_shell

